package view.dialogs.modeler;

import java.awt.Frame;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * this is a generic window for chains, filters and pipes.
 * @author skuarch
 */
public class GenericBorrar extends JDialog {

    //==========================================================================
    /**
     * Creates new form Chains
     */
    public GenericBorrar(Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(getContentPane());


        /*
         * table.addMouseListener(new MouseAdapter() {
         *
         * @Override public void mouseClicked(MouseEvent e) {
         * super.mouseClicked(e);
         *
         * JTable t = (JTable) e.getSource(); int row =
         * t.rowAtPoint(e.getPoint()); int col = t.columnAtPoint(e.getPoint());
         *
         * System.out.println("que pedo: " + row + " " + col);
         * System.out.println("value " + t.getValueAt(row, col));
         *
         * }
         * });
         */

    }

    //==========================================================================
    public void setEnableButtonNewChain(boolean flag) {
        jButtonNew.setEnabled(flag);
    }

    //==========================================================================
    public void setEnableButtonClose(boolean flag) {
        jButtonClose.setEnabled(flag);
    }

    //==========================================================================
    public void setTable(JTable table) {
        this.table = table;
    }

    //==========================================================================
    public JTable getTable() {
        return this.table;
    }

    //==========================================================================
    public void setTableModel(DefaultTableModel tableModel) {
        table.setModel(tableModel);
    }

    //==========================================================================
    public void addActionListenerButtonNew(ActionListener actionListener) {
        jButtonNew.addActionListener(actionListener);
    }

    //==========================================================================
    public void setAutoCreateRowSorter(boolean flag) {
        table.setAutoCreateRowSorter(flag);

    }

    //==========================================================================
    public void setIndeterminateProgressBar(boolean flag) {
        jProgressBar.setIndeterminate(flag);
    }
    
    public JScrollPane getJScrollPane(){
        return this.jScrollPane2;
    }

    //==========================================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNew = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chains");

        jButtonNew.setText("create a new chain");

        jButtonClose.setText("close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null, null},
                {null, null, null, null,null, null},
                {null, null, null, null,null, null},
                {null, null, null, null,null, null}
            },
            new String [] {
                "id", "Chain name", "Service level", "Fallback" ,"Status" , "Options"
            }
        ));
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNew))
                    .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNew)
                    .addComponent(jButtonClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //==========================================================================
    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}