package view.dialogs;

import controllers.ControllerConfiguration;
import java.awt.Frame;
import javax.swing.JDialog;
import model.beans.User;
import view.notifications.Notifications;

/**
 *
 * @author skuarch
 */
public class Configuration extends JDialog {
    
    private Notifications notifications = null;
    private model.beans.Configuration configuration = null;

    //==========================================================================
    /**
     * Creates new form Configuration
     */
    public Configuration(Frame parent, boolean modal) {
        super(parent, modal);
        notifications = new Notifications();
        initComponents();
        setLocationRelativeTo(getRootPane());
        onLoad();
    }

    //==========================================================================
    private void onLoad() {

        try {

            this.configuration = new ControllerConfiguration().getInitialConfiguration();
            jTextFieldProjectName.setText(configuration.getProjectName());
            jTextFieldTWC.setText(configuration.getJmsTimeWaitConnectivity() / 1000 + "");
            jTextFieldTWM.setText(configuration.getJmsTimeWaitMessage() / 1000 + "");
            jTextFieldURLHelp.setText(configuration.getHelpPath());
            jTextFieldURLSSN.setText(configuration.getJWSPath());
            jTextFieldLiveUpdate.setText(configuration.getSecondsLive());
            jTextFieldMasterShaper.setText(configuration.getUsedMasterShaper());
            jTextFieldMasterShaperServer.setText(configuration.getMasterShaperServer());
            
            // the user has a privileges
            if (User.getInstance().getLevel() == 2) {
                jButtonSave.setEnabled(false);
                jButtonSave.setVisible(false);
                jLabelMessage.setText("you don't have privileges for change these settings");
            }

        } catch (Exception e) {
            notifications.error("error ", e);
        }

    }

    //==========================================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jTextFieldProjectName = new javax.swing.JTextField();
        jTextFieldTWM = new javax.swing.JTextField();
        jTextFieldTWC = new javax.swing.JTextField();
        jTextFieldURLHelp = new javax.swing.JTextField();
        jTextFieldURLSSN = new javax.swing.JTextField();
        jTextFieldLiveUpdate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMasterShaper = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMasterShaperServer = new javax.swing.JTextField();

        jTextField11.setText("jTextField11");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration");

        jTextFieldProjectName.setEditable(false);

        jLabel10.setText("Project name");

        jLabel11.setText("Time to wait message");

        jLabel12.setText("Time to wait connectivity");

        jLabel13.setText("URL help");

        jLabel14.setText("URL SSN");

        jLabel15.setText("Live Update");

        jButtonSave.setText("save configuration");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelMessage.setForeground(new java.awt.Color(0, 20, 255));

        jLabel1.setText("seconds");

        jLabel2.setText("seconds");

        jLabel3.setText("seconds");

        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Use shaper");

        jLabel5.setText("Shaper server");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldProjectName, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(jTextFieldTWM)
                            .addComponent(jTextFieldTWC)
                            .addComponent(jTextFieldURLHelp)
                            .addComponent(jTextFieldLiveUpdate)
                            .addComponent(jTextFieldURLSSN)
                            .addComponent(jTextFieldMasterShaper)
                            .addComponent(jTextFieldMasterShaperServer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTWM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTWC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldURLHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldURLSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLiveUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMasterShaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMasterShaperServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jLabelMessage)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //==========================================================================
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    //==========================================================================

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {

        model.beans.Configuration c = null;

        try {

            c = new model.beans.Configuration();
            c.setProjectName(jTextFieldProjectName.getText());
            c.setHelpPath(jTextFieldURLHelp.getText());
            c.setJWSPath(jTextFieldURLSSN.getText());
            c.setJmsTimeWaitConnectivity(Integer.parseInt(jTextFieldTWC.getText()) * 1000);
            c.setJmsTimeWaitMessage(Integer.parseInt(jTextFieldTWM.getText()) * 1000);
            c.setSecondsLive(jTextFieldLiveUpdate.getText());
            c.setUsedMasterShaper(jTextFieldMasterShaper.getText());
            c.setMasterShaperServer(jTextFieldMasterShaperServer.getText());

            new controllers.ControllerConfiguration().truncateConfiguration();
            new controllers.ControllerConfiguration().saveConfiguration(c);

            jLabelMessage.setText("Done !!");
            
        } catch (Exception e) {
            notifications.error("error saving the new configuration", e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextFieldLiveUpdate;
    private javax.swing.JTextField jTextFieldMasterShaper;
    private javax.swing.JTextField jTextFieldMasterShaperServer;
    private javax.swing.JTextField jTextFieldProjectName;
    private javax.swing.JTextField jTextFieldTWC;
    private javax.swing.JTextField jTextFieldTWM;
    private javax.swing.JTextField jTextFieldURLHelp;
    private javax.swing.JTextField jTextFieldURLSSN;
    // End of variables declaration//GEN-END:variables
}
